# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # This mypy step is not perfect; in the interest of not reproducing the entire
  # dependency list here we only install `attrs`. It will catch a useful subset
  # of errors but does not replace a full mypy run (either locally or in CI).
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        additional_dependencies: [attrs]

  - repo: https://github.com/psf/black
    rev: '22.12.0'
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.243
    hooks:
    - id: ruff
