# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Start with the basic pre-commit hooks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Then others in alphabetical order:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    # This mypy step is not perfect; in the interest of not reproducing
    # the entire dependency list here we only install `attrs`. It will catch
    # a useful subset of errors but does not replace a full mypy run
    # (either locally or in CI).
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [attrs]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        # For now we let this act on all files; if need be we can restrict it
        # with `types_or` in the future.

  - repo: https://github.com/psf/black
    rev: "23.9.1"
    hooks:
      - id: black
