# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Start with the basic pre-commit hooks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Then others in alphabetical order:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    # This mypy step is not perfect; in the interest of not reproducing
    # the entire dependency list here we only install `attrs`. It will catch
    # a useful subset of errors but does not replace a full mypy run
    # (either locally or in CI).
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [attrs]

  - repo: https://github.com/psf/black
    rev: "25.1.0"
    hooks:
      - id: black

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22  # Use the ref you want to point at
    hooks:
    - id: mdformat
