#!/bin/sh

# Generates requirements-pyX.X.txt files based on a fresh install from PyPI.
# Uses conda to install independent Pythons.

set -ex
eval "$(conda shell.bash hook)"
cd "$(dirname "$0")/.."
TEMPDIR="$(mktemp -d)"
trap "trash $TEMPDIR" EXIT

# The version of Python we want to run lints under.
LINTVER=3.7

for PYVER in 3.7 3.8 3.9 3.10; do
  CONDIR="$TEMPDIR/py-$PYVER"
  conda create -y -p "$CONDIR" "python=$PYVER"
  (
    conda activate "$CONDIR"
    pip install .
    pip freeze --exclude somacore >"./python-spec/requirements-py$PYVER.txt"
  )
done

CONDIR="$TEMPDIR/py-$LINTVER-lint"
conda create -y -p "$CONDIR" "python=$LINTVER"
(
  conda activate "$CONDIR"
  pip install .[dev] mypy pre-commit
  mypy --install-types --non-interactive ./python-spec/src
  pip freeze --exclude somacore >"./python-spec/requirements-py$LINTVER-lint.txt"
)
