#!/bin/sh

# Generates requirements-pyX.X.txt files based on a fresh install from PyPI.
# Uses conda to install independent Pythons.

set -ex
cd "$(dirname "$0")/.."
TEMPDIR="$(mktemp -d)"
trap "trash $TEMPDIR" EXIT

# The version of Python we want to run lints under.
LINTVER=3.7

for PYVER in 3.7 3.8 3.9 3.10; do
  CONDIR="$TEMPDIR/py-$PYVER"
  conda create -y -p "$CONDIR" "python=$PYVER"
  conda run -p "$CONDIR" pip install .
  conda run -p "$CONDIR" pip freeze --exclude somacore >"./python-spec/requirements-py$PYVER.txt"
done

CONDIR="$TEMPDIR/py-$LINTVER-lint"
conda create -y -p "$CONDIR" "python=$LINTVER"
conda run -p "$CONDIR" pip install .[dev] mypy
conda run -p "$CONDIR" mypy --install-types --non-interactive ./python-spec/src
conda run -p "$CONDIR" pip freeze --exclude somacore >"./python-spec/requirements-py$LINTVER-lint.txt"
