name: python-somacore

on:
  pull_request:
    branches: ["*"]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  format-check:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: python-spec/requirements-py${{ env.PYTHON_VERSION }}-lint.txt
      - uses: psf/black@stable
      - name: Install static analysis packages
        run: |
          pip install -r python-spec/requirements-py${{ env.PYTHON_VERSION }}-lint.txt
      - name: Run mypy
        run: mypy ./python-spec/src
      - name: Run ruff
        run: ruff .

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          # setuptools-scm needs a deep clone so it can look through history
          # to find a relevant tag.
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: python-spec/requirements-py${{ matrix.python-version }}.txt
      - name: Install prereqs
        run: |
          pip install --upgrade pip wheel pytest pytest-cov setuptools
          pip install -r python-spec/requirements-py${{ matrix.python-version }}.txt
          pip install .
      - name: Run tests
        working-directory: ./python-spec
        run: |
          pytest -s -v --junitxml=junit/test-results.xml --cov somacore --cov-report=xml --cov-report=html

  upload-to-pypi:
    needs:
      - format-check
      - run-tests
    # Run only when tagging a release that starts with `python-`.
    if: >
      github.event_name == 'release'
      && github.event.action == 'published'
      && startsWith(github.event.release.tag_name, 'python-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: pip
          cache-dependency-path: python-spec/requirements-py3.10.txt
          python-version: '3.10'
      - name: Set up environment
        run: |
          pip install --upgrade build pip wheel setuptools setuptools-scm
          python -m build .
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist
