name: python-somacore

on:
  pull_request:
    branches: ["*"]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: psf/black@stable
        with:
          src: "./python-spec"
      - uses: isort/isort-action@v1
        with:
          sort-paths: "./python-spec"

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # cache: pip  # TODO: Enable after creating requirements.txt files.
      - name: Install prereqs
        run: |
          pip install --upgrade pip wheel pytest pytest-cov setuptools
      - name: Run tests
        run: |
          cd python-spec
          pip install .
          pytest -s -v --junitxml=junit/test-results.xml --cov somacore --cov-report=xml --cov-report=html

  upload-to-pypi:
    needs:
      - format-check
      - run-tests
    # Run only when tagging a release that starts with `python-`.
    if: >
      github.event_name == 'release'
      && github.event.action == 'published'
      && startsWith(github.event.release.tag_name, 'python-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        # with:
        #   cache: pip  # TODO: Enable after creating requirements.txt files.
      - name: Set up environment
        run: |
          pip install --upgrade build pip wheel setuptools setuptools-scm
          ./python-spec/write-version-file
          python -m build python-spec
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: python-spec/dist
